"""predicts

Revision ID: 244d946c3f9d
Revises: 45881bb9b444
Create Date: 2025-05-05 01:17:51.027296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '244d946c3f9d'
down_revision: Union[str, None] = '45881bb9b444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current_predict', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('current_predict', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.add_column('current_predict', sa.Column('act_date', sa.Date(), nullable=True))
    op.add_column('current_predict', sa.Column('warehouse_weight', sa.Float(), nullable=True))
    op.add_column('current_predict', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('current_predict', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.add_column('current_predict', sa.Column('forming_date', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'current_predict', 'brand', ['brand_id'], ['id'])
    op.drop_column('current_predict', 'date')
    op.add_column('predict', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('predict', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.add_column('predict', sa.Column('act_date', sa.Date(), nullable=True))
    op.add_column('predict', sa.Column('warehouse_weight', sa.Float(), nullable=True))
    op.add_column('predict', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('predict', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.add_column('predict', sa.Column('forming_date', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'predict', 'brand', ['brand_id'], ['id'])
    op.drop_column('predict', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predict', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'predict', type_='foreignkey')
    op.drop_column('predict', 'forming_date')
    op.drop_column('predict', 'end_time')
    op.drop_column('predict', 'start_time')
    op.drop_column('predict', 'warehouse_weight')
    op.drop_column('predict', 'act_date')
    op.drop_column('predict', 'brand_id')
    op.drop_column('predict', 'id')
    op.add_column('current_predict', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'current_predict', type_='foreignkey')
    op.drop_column('current_predict', 'forming_date')
    op.drop_column('current_predict', 'end_time')
    op.drop_column('current_predict', 'start_time')
    op.drop_column('current_predict', 'warehouse_weight')
    op.drop_column('current_predict', 'act_date')
    op.drop_column('current_predict', 'brand_id')
    op.drop_column('current_predict', 'id')
    # ### end Alembic commands ###
