"""fix warehouse

Revision ID: 3ddab569c6ae
Revises: ab79607bc920
Create Date: 2025-05-04 18:55:10.832131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ddab569c6ae'
down_revision: Union[str, None] = 'ab79607bc920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stack', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('stack', 'warehouse_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('uix_stack_warehouse_name', 'stack', ['warehouse_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_stack_warehouse_name', 'stack', type_='unique')
    op.alter_column('stack', 'warehouse_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stack', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
