"""predicts

Revision ID: 488789e9f0d4
Revises: 244d946c3f9d
Create Date: 2025-05-05 01:31:46.226100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '488789e9f0d4'
down_revision: Union[str, None] = '244d946c3f9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current_predict', sa.Column('date', sa.Date(), nullable=True))
    op.drop_column('current_predict', 'start_time')
    op.drop_column('current_predict', 'end_time')
    op.drop_column('current_predict', 'warehouse_weight')
    op.drop_column('current_predict', 'act_date')
    op.drop_column('current_predict', 'forming_date')
    op.add_column('predict', sa.Column('date', sa.Date(), nullable=True))
    op.drop_column('predict', 'start_time')
    op.drop_column('predict', 'end_time')
    op.drop_column('predict', 'warehouse_weight')
    op.drop_column('predict', 'act_date')
    op.drop_column('predict', 'forming_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predict', sa.Column('forming_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('predict', sa.Column('act_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('predict', sa.Column('warehouse_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('predict', sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('predict', sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('predict', 'date')
    op.add_column('current_predict', sa.Column('forming_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('current_predict', sa.Column('act_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('current_predict', sa.Column('warehouse_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('current_predict', sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('current_predict', sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('current_predict', 'date')
    # ### end Alembic commands ###
