"""predicts

Revision ID: 7482c22c6745
Revises: 488789e9f0d4
Create Date: 2025-05-05 01:37:46.837854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7482c22c6745'
down_revision: Union[str, None] = '488789e9f0d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current_predict', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('predict', sa.Column('weight', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predict', 'weight')
    op.drop_column('current_predict', 'weight')
    # ### end Alembic commands ###
