"""Add predict & current predict  table

Revision ID: c0d384c2738c
Revises: 39e7b806fdc2
Create Date: 2025-05-04 16:36:49.612253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0d384c2738c'
down_revision: Union[str, None] = '39e7b806fdc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_predict',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('stack_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stack_id'], ['stack.id'], ),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('predict',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('stack_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stack_id'], ['stack.id'], ),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predict')
    op.drop_table('current_predict')
    # ### end Alembic commands ###
