"""unique brand

Revision ID: d86a2f17c56f
Revises: 3ddab569c6ae
Create Date: 2025-05-04 20:38:54.530700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd86a2f17c56f'
down_revision: Union[str, None] = '3ddab569c6ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'brand', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'brand', type_='unique')
    # ### end Alembic commands ###
