"""fix supplies

Revision ID: da1ea2ec0123
Revises: d1fb6fc6a3fa
Create Date: 2025-05-04 18:19:10.514749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da1ea2ec0123'
down_revision: Union[str, None] = 'd1fb6fc6a3fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temperature', sa.Column('stack_id', sa.Integer(), nullable=True))
    op.drop_constraint('temperature_warehouse_id_fkey', 'temperature', type_='foreignkey')
    op.create_foreign_key(None, 'temperature', 'stack', ['stack_id'], ['id'])
    op.drop_column('temperature', 'stack_number')
    op.drop_column('temperature', 'warehouse_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temperature', sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('temperature', sa.Column('stack_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'temperature', type_='foreignkey')
    op.create_foreign_key('temperature_warehouse_id_fkey', 'temperature', 'warehouse', ['warehouse_id'], ['id'])
    op.drop_column('temperature', 'stack_id')
    # ### end Alembic commands ###
