"""Add stack table

Revision ID: ea10ce0ad6bd
Revises: bd85aeaadd1b
Create Date: 2025-05-04 12:52:05.984775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea10ce0ad6bd'
down_revision: Union[str, None] = 'bd85aeaadd1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stack_warehouse_id_key', 'stack', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('stack_warehouse_id_key', 'stack', ['warehouse_id'])
    # ### end Alembic commands ###
